<h1>Help &gt; Block &gt; local.xml</h1>

<h2>Basics</h2>
<p>
	We strongly encourage you to follow the local.xml convention and place your layout overrides in a file called local.xml
	in the "layout" folder of your custom theme. 
</p>

<p>
	To enforce this policy, many parts of these tools will not allow you to modify core files directly,
	but will instead offer to create certain custom files for you, including local.xml.
<p>

<p>For this to work, you need to <a href="<?php echo $this->getHelpUrl('theme/create_custom') ?>">create a custom theme</a>.</p>

<p>References:</p>
<ul>
	<li><a href="<?php echo $this->getHelpUrl('theme/create_custom') ?>">Create a custom theme</a></li>
</ul>