<h1>Help &gt; Panels &gt; Editor &gt; Usage</h1>

<h2>Basics</h2>
<p><strong>Upon first load, the <em>Editor</em> panel will be empty (or contain this help text).</strong></p>

<p>To load a file in the editor, you can do one of the following:</p>
<ul>
	<li><a href="<?php echo $this->getHelpUrl('blocks/inspect') ?>">Inspect a block</a></li>
	<li><a href="<?php echo $this->getHelpUrl('layouts/local_xml') ?>">Edit your layout's local.xml</a></li>
</ul>