<div id="dhmedia_devel_block_frontend">
	
	<a
		class="dhlink"
		target="_blank"
		title="Doghouse Media - Perth based web agency and Magento specialists"
		href="http://www.dhmedia.com.au/?ref=magento-toolbar">
		<span>by </span>
		Doghouse Media
	</a>
	
	<div class="update-notifier-box has-sprite sprite-small icon-important"></div>
	
	<ul>
		<li>
			<a
				href="<?php echo Mage::getBaseUrl() ?>devel/command/clearcache?return=<?php echo $this->helper('devel/url')->getCurrentUrl() ?>"
				class="has-sprite sprite-small icon-important">
				Clear cache
			</a>
		</li>
		<li>
			<a
				href="<?php echo Mage::getBaseUrl() ?>devel/command/reindex?return=<?php echo $this->helper('devel/url')->getCurrentUrl() ?>"
				class="has-sprite sprite-small icon-reindex">
				Re-index
			</a>
		</li>
		<li>
			<a
				href="<?php echo Mage::getBaseUrl() ?>devel/command/hintson?return=<?php echo $this->helper('devel/url')->getCurrentUrl() ?>" 
				class="has-sprite sprite-small icon-hints">
				Hints on
			</a>
		</li>
		<li>
			<a
				href="<?php echo Mage::getBaseUrl() ?>devel/command/hintsoff?return=<?php echo $this->helper('devel/url')->getCurrentUrl() ?>"
				class="has-sprite sprite-small icon-hints">
				Hints off
			</a>
		</li>
		
		<li>
			<a
				href="http://docs.magentocommerce.com"
				onclick="DevelGlobals.PanelManager.get('dhmedia_devel_block_panel_docs').open(this.href); return false;"
				class="has-sprite sprite-small icon-documentation">
				Docs
			</a>
		</li>
		
		<li>
			<a href="#"  class="has-sprite sprite-small icon-executephp">Execute PHP</a>
			<div class="show-on-hover">
				<form action="<?php echo Mage::getBaseUrl() ?>devel/command/execphp">
					<textarea name="php"></textarea>
					<input type="submit" value="Execute" />
					<div class="clear-fix"></div>
					<div class="result"></div>
				</form>
			</div>
		</li>
		
		<li>
			<a href="#" class="has-sprite sprite-small icon-themeinfo">Theme info</a>
			<div class="show-on-hover">
				<table>
					<tr>
						<th>Store</th>
						<td><?php echo Mage::getDesign()->getStore()->getId() ?></td>
					</tr>
					<tr>	
						<th>Area</th>
						<td><?php echo Mage::getDesign()->getArea() ?></td>
					</tr>
					<tr>	
						<th>Package</th>
						<td><?php echo Mage::getDesign()->getPackageName() ?></td>
					</tr>
					<tr>
						<th>Theme</th>
						<td><?php echo Mage::getDesign()->getTheme('frontend') ?></td>
					</tr>
					<tr>
						<th>Theme list</th>
						<td><pre><?php print_r(Mage::getDesign()->getThemeList()) ?></pre></td>
					</tr>
					<tr>	
						<th>Base dir</th>
						<td><?php echo Mage::getBaseDir('design') ?></td>
					</tr>
					<tr>
						<th>Skin url</th>
						<td><?php echo $this->getSkinUrl('') ?></td>
					</tr>
				</table>
			</div>
		</li>
		
		<li>
			<a
				href="<?php echo Mage::getBaseUrl() ?>devel/filesystem/edit/type/layout?layout=local.xml"
				onclick="DevelGlobals.PanelManager.get('dhmedia_devel_block_panel_editor').open(this.href); return false;"
				class="has-sprite sprite-small icon-layoutxml">
				local.xml
			</a>
		</li>
	</ul>
	
	<div class="clear-fix"></div>
	
</div>

<div id="dhmedia_devel_block_panels">
	<div id="dhmedia_devel_block_panel_admin" class="devel-panel" title="Admin"
		data-button-class="sprite-small icon-settings">
		<iframe id="devel-admin" src="<?php echo Mage::getBaseUrl() . $this->getAdminPath() ?>"></iframe>
	</div>
	
	<div id="dhmedia_devel_block_panel_docs" class="devel-panel" title="Docs"
		data-button-class="sprite-small icon-documentation">
		<iframe id="devel-docs" src="http://docs.magentocommerce.com"></iframe>
	</div>
	
	<div id="dhmedia_devel_block_panel_editor" class="devel-panel" title="Editor"
		data-button-class="sprite-small icon-editor">
		<iframe id="devel-editor" 
			src="<?php echo $this->helper('devel/url')->getHelpUrl('panels/editor/usage') ?>">
		</iframe>
	</div>
	
	<div id="dhmedia_devel_block_panel_block" class="devel-panel" title="Block" 
		data-button-class="sprite-small icon-blocks">
		<iframe id="devel-block"
			src="<?php echo $this->helper('devel/url')->getHelpUrl('panels/block/usage') ?>">
		</iframe>
	</div>
	
	<div id="dhmedia_devel_block_panel_xml" class="devel-panel" title="Xml" 
		data-button-class="sprite-small icon-layoutxml">
<!--
You can't tab or space the following textarea without 
creating problems with the editor. Putting in all on
one line works too.
-->
<textarea id="layout-xml" name="layout-xml">
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n" ?>
<?php echo $this->getLayoutXml() ?>
</textarea>
	</div>
</div>

<script type="text/javascript">

document.observe("dom:loaded", function()
{
	new DevelForms('#dhmedia_devel_block_frontend form');

	new DevelHintBlock('.devel-hint .hints .hint[rel="block"]');
	new DevelHintTemplate('.devel-hint .hints .hint[rel="template"]');
	
	DevelGlobals.PanelManager = new DevelPanelManager('#dhmedia_devel_block_panels', {
		container: {
			css: {
				marginLeft: '-1ex'
			}
		},
		panel: {
			selector: '.devel-panel'
		}
	});

	new DevelUpdateNotifier('#dhmedia_devel_block_frontend .update-notifier-box',
		'<?php echo Mage::getBaseUrl() ?>devel/self/hasupdate'
	);

	new DevelSprites('.has-sprite');
});

var DevelGlobals = {};
	
</script>

<!--  START Code Mirror editor -->
<style>
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/lib/codemirror.css"); 
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/xml/xml.css");
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/javascript/javascript.css"); 
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/css/css.css");
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/clike/clike.css");

	.CodeMirror { height: auto; }
	#dhmedia_devel_block_panel_xml .CodeMirror { height: 100%; }
</style>
	
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/lib/codemirror.js"></script> 
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/xml/xml.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/javascript/javascript.js"></script> 
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/css/css.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/clike/clike.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/php/php.js"></script>

<script type="text/javascript">
CodeMirror.fromTextArea(document.getElementById("layout-xml"), {
    lineNumbers: true,
    matchBrackets: true,
    mode: "application/xml",
    indentUnit: 8,
    indentWithTabs: true,
    enterMode: "keep",
    tabMode: "shift",
    readOnly: true
});
</script>
<!--  END Code Mirror editor -->