<div id="dhmedia_devel_block_frontend">
	
	<a
		class="dhlink"
		target="_blank"
		title="Doghouse Media - Perth based web agency and Magento specialists"
		href="http://www.dhmedia.com.au/?ref=magento-toolbar">
		<span>by </span>
		Doghouse Media
	</a>
	
	<div class="update-notifier-box has-sprite sprite-small icon-important"></div>
	
	<?php echo $this->getChildHtml('menu') ?>
	
	<div class="clear-fix"></div>
	
</div>

<div id="dhmedia_devel_block_panels">
	
	<!--  These blocks are only here for reference. Remove when panel refactoring is done. -->
	
	<div id="dhmedia_devel_block_panel_editor" class="devel-panel" title="Editor"
		data-button-class="sprite-small icon-editor">
		<iframe id="devel-editor" 
			src="<?php echo $this->helper('devel/url')->getHelpUrl('panels/editor/usage') ?>">
		</iframe>
	</div>
	
	<div id="dhmedia_devel_block_panel_block" class="devel-panel" title="Block" 
		data-button-class="sprite-small icon-blocks">
		<iframe id="devel-block"
			src="<?php echo $this->helper('devel/url')->getHelpUrl('panels/block/usage') ?>">
		</iframe>
	</div>
	
	<div id="dhmedia_devel_block_panel_xml" class="devel-panel" title="Xml" 
		data-button-class="sprite-small icon-layoutxml">
<!--
You can't tab or space the following textarea without 
creating problems with the editor. Putting in all on
one line works too.
-->
<textarea id="layout-xml" name="layout-xml">
<?php echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n" ?>
<?php echo $this->getLayoutXml() ?>
</textarea>
	</div>
</div>

<script type="text/javascript">

document.observe("dom:loaded", function()
{
	new DevelForms('#dhmedia_devel_block_frontend form');

	DevelGlobals.DevelHints = new DevelHints('.devel-hint', '.devel-hint .hints');
	
	DevelGlobals.PanelManager = new DevelPanelManager('#dhmedia_devel_block_panels', {
		container: {
			css: {
				marginLeft: '-1ex'
			}
		}
	});

	new DevelUpdateNotifier('#dhmedia_devel_block_frontend .update-notifier-box',
		'<?php echo $this->helper('devel/url')->getUrl('self/hasupdate') ?>'
	);

	new DevelSprites('.has-sprite');
});

var DevelGlobals = {};
	
</script>

<!--  START Code Mirror editor -->
<style>
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/lib/codemirror.css"); 
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/xml/xml.css");
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/javascript/javascript.css"); 
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/css/css.css");
	@import url("<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/clike/clike.css");

	.CodeMirror { height: auto; }
	#dhmedia_devel_block_panel_xml .CodeMirror { height: 100%; }
</style>
	
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/lib/codemirror.js"></script> 
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/xml/xml.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/javascript/javascript.js"></script> 
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/css/css.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/clike/clike.js"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/php/php.js"></script>

<script type="text/javascript">
CodeMirror.fromTextArea(document.getElementById("layout-xml"), {
    lineNumbers: true,
    matchBrackets: true,
    mode: "application/xml",
    indentUnit: 8,
    indentWithTabs: true,
    enterMode: "keep",
    tabMode: "shift",
    readOnly: true
});
</script>
<!--  END Code Mirror editor -->