<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!doctype html>
<html>
<head>
    <?php echo $this->getChildHtml('head') ?>
    
	<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>codemirror/lib/codemirror.css" media="all" /> 
	<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/xml/xml.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/javascript/javascript.css" media="all" /> 
	<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/css/css.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/clike/clike.css" media="all" /> 
	
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/lib/codemirror.js"></script> 
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/xml/xml.js"></script>
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/javascript/javascript.js"></script> 
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/css/css.js"></script>
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/clike/clike.js"></script>
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>codemirror/mode/php/php.js"></script>
	
	<style type="text/css">
		html { margin:0; padding: 0;}
		body.page-empty { padding: 1%; height: 98%; margin: 0; background: #fcfcfc; text-align: left; }
		.devel-hint { display: none; }
	</style>
</head>
<body class="page-empty <?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
    <div>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('content') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
    </div>
</body>
</html>
