<h1>Help &gt; Create custom theme</h1>

<p>To override Magento correctly, you need to use your <em>own</em> theme.</p>

<p><em>Advanced Developer Tools</em> can usually create all the folders and files you need, but you need to tell Magento what the name of your theme is going to be.</p>

<p>Go to <em>System &gt; Configuration &gt; Design</em> and switch to the <em>Main Website</em>.  Under <em>Themes &gt; Default</em> enter the name you want to use for your default theme.  Remember this will be used for folder names and xml tags, so keep it simple: just letters and numbers, no spaces, etc...</p>
