<h1>Help &gt; Panels &gt; Block &gt; Usage</h1>

<h2>Basics</h2>
<p>
	<strong>Upon first load, the <em>Block</em> panel will be empty (or contain this help text).</strong>
	You need to <a href="<?php echo $this->getHelpUrl('blocks/inspect') ?>">inspect a block</a> for the panel to populate with info about the block.
</p>

<p>References:</p>
<ul>
	<li><a href="<?php echo $this->getHelpUrl('blocks/inspect') ?>">How to inspect a block</a></li>
</ul>
